export declare const useActiveModelStore: import("pinia").StoreDefinition<"active-model", Pick<{
    configured: import("vue").ComputedRef<boolean>;
    activeProvider: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeModel: import("@vueuse/shared").ManualResetRefReturn<string>;
    customModelName: import("@vueuse/shared").ManualResetRefReturn<string>;
    expandedDescriptions: import("@vueuse/shared").ManualResetRefReturn<Record<string, boolean>>;
    modelSearchQuery: import("@vueuse/shared").ManualResetRefReturn<string>;
    supportsModelListing: import("vue").ComputedRef<boolean>;
    providerModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    isLoadingActiveProviderModels: import("vue").ComputedRef<boolean>;
    activeProviderModelError: import("vue").ComputedRef<string | null>;
    filteredModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    resetModelSelection: () => void;
    loadModelsForProvider: (provider: string) => Promise<void>;
    getModelsForProvider: (provider: string) => Promise<import("..").ModelInfo[]>;
    resetState: () => void;
}, "activeProvider" | "activeModel" | "customModelName" | "expandedDescriptions" | "modelSearchQuery">, Pick<{
    configured: import("vue").ComputedRef<boolean>;
    activeProvider: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeModel: import("@vueuse/shared").ManualResetRefReturn<string>;
    customModelName: import("@vueuse/shared").ManualResetRefReturn<string>;
    expandedDescriptions: import("@vueuse/shared").ManualResetRefReturn<Record<string, boolean>>;
    modelSearchQuery: import("@vueuse/shared").ManualResetRefReturn<string>;
    supportsModelListing: import("vue").ComputedRef<boolean>;
    providerModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    isLoadingActiveProviderModels: import("vue").ComputedRef<boolean>;
    activeProviderModelError: import("vue").ComputedRef<string | null>;
    filteredModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    resetModelSelection: () => void;
    loadModelsForProvider: (provider: string) => Promise<void>;
    getModelsForProvider: (provider: string) => Promise<import("..").ModelInfo[]>;
    resetState: () => void;
}, "configured" | "supportsModelListing" | "providerModels" | "isLoadingActiveProviderModels" | "activeProviderModelError" | "filteredModels">, Pick<{
    configured: import("vue").ComputedRef<boolean>;
    activeProvider: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeModel: import("@vueuse/shared").ManualResetRefReturn<string>;
    customModelName: import("@vueuse/shared").ManualResetRefReturn<string>;
    expandedDescriptions: import("@vueuse/shared").ManualResetRefReturn<Record<string, boolean>>;
    modelSearchQuery: import("@vueuse/shared").ManualResetRefReturn<string>;
    supportsModelListing: import("vue").ComputedRef<boolean>;
    providerModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    isLoadingActiveProviderModels: import("vue").ComputedRef<boolean>;
    activeProviderModelError: import("vue").ComputedRef<string | null>;
    filteredModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    resetModelSelection: () => void;
    loadModelsForProvider: (provider: string) => Promise<void>;
    getModelsForProvider: (provider: string) => Promise<import("..").ModelInfo[]>;
    resetState: () => void;
}, "resetState" | "getModelsForProvider" | "resetModelSelection" | "loadModelsForProvider">>;
