import type { SpeechProviderWithExtraOptions } from '@xsai-ext/providers/utils';
import type { VoiceInfo } from '../providers';
import type { VoicePackParams, VoicePackSnapshot } from './persona';
export declare function toSignedPercent(value: number): string;
interface VoicePackSpeechInputOptions {
    text: string;
    voice: VoiceInfo;
    providerConfig?: Record<string, unknown>;
    params?: VoicePackParams;
    voicePack?: Pick<VoicePackSnapshot, 'packId' | 'costMultiplier'>;
    forceSSML?: boolean;
    supportsSSML?: boolean;
    supportsAdapterProsody?: boolean;
}
interface VoicePackSpeechInput {
    input: string;
    providerConfig: Record<string, unknown>;
}
export declare function voicePackForSpeechProvider(_providerId: string | undefined, _voicePack: VoicePackSnapshot | undefined): VoicePackSnapshot | undefined;
export declare const useSpeechStore: import("pinia").StoreDefinition<"speech", Pick<{
    configured: import("vue").ComputedRef<boolean>;
    activeSpeechProvider: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeSpeechModel: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeSpeechVoice: import("@vueuse/shared").ManualResetRefReturn<VoiceInfo | undefined>;
    activeSpeechVoiceId: import("@vueuse/shared").ManualResetRefReturn<string>;
    pitch: import("@vueuse/shared").ManualResetRefReturn<number>;
    rate: import("@vueuse/shared").ManualResetRefReturn<number>;
    ssmlEnabled: import("@vueuse/shared").ManualResetRefReturn<boolean>;
    isLoadingSpeechProviderVoices: import("@vueuse/shared").ManualResetRefReturn<boolean>;
    speechProviderError: import("@vueuse/shared").ManualResetRefReturn<string | null>;
    availableVoices: import("@vueuse/shared").ManualResetRefReturn<Record<string, VoiceInfo[]>>;
    modelSearchQuery: import("@vueuse/shared").ManualResetRefReturn<string>;
    availableSpeechProvidersMetadata: import("vue").ComputedRef<import("..").ProviderMetadata[]>;
    supportsSSML: import("vue").ComputedRef<boolean>;
    supportsModelListing: import("vue").ComputedRef<boolean>;
    providerModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    isLoadingActiveProviderModels: import("vue").ComputedRef<boolean>;
    activeProviderModelError: import("vue").ComputedRef<string | null>;
    filteredModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    speech: (provider: SpeechProviderWithExtraOptions<string, any>, model: string, input: string, voice: string, providerConfig?: Record<string, any>) => Promise<ArrayBuffer>;
    loadVoicesForProvider: (provider: string, model?: string) => Promise<VoiceInfo[]>;
    getVoicesForProvider: (provider: string) => VoiceInfo[];
    ensureActiveSpeechModel: () => void;
    generateSSML: (text: string, voice: VoiceInfo, providerConfig?: Record<string, unknown>) => string;
    resolveVoicePackSpeechInput: (options: VoicePackSpeechInputOptions) => VoicePackSpeechInput;
    resetState: () => void;
}, "pitch" | "rate" | "modelSearchQuery" | "activeSpeechProvider" | "activeSpeechModel" | "activeSpeechVoice" | "activeSpeechVoiceId" | "ssmlEnabled" | "isLoadingSpeechProviderVoices" | "speechProviderError" | "availableVoices">, Pick<{
    configured: import("vue").ComputedRef<boolean>;
    activeSpeechProvider: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeSpeechModel: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeSpeechVoice: import("@vueuse/shared").ManualResetRefReturn<VoiceInfo | undefined>;
    activeSpeechVoiceId: import("@vueuse/shared").ManualResetRefReturn<string>;
    pitch: import("@vueuse/shared").ManualResetRefReturn<number>;
    rate: import("@vueuse/shared").ManualResetRefReturn<number>;
    ssmlEnabled: import("@vueuse/shared").ManualResetRefReturn<boolean>;
    isLoadingSpeechProviderVoices: import("@vueuse/shared").ManualResetRefReturn<boolean>;
    speechProviderError: import("@vueuse/shared").ManualResetRefReturn<string | null>;
    availableVoices: import("@vueuse/shared").ManualResetRefReturn<Record<string, VoiceInfo[]>>;
    modelSearchQuery: import("@vueuse/shared").ManualResetRefReturn<string>;
    availableSpeechProvidersMetadata: import("vue").ComputedRef<import("..").ProviderMetadata[]>;
    supportsSSML: import("vue").ComputedRef<boolean>;
    supportsModelListing: import("vue").ComputedRef<boolean>;
    providerModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    isLoadingActiveProviderModels: import("vue").ComputedRef<boolean>;
    activeProviderModelError: import("vue").ComputedRef<string | null>;
    filteredModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    speech: (provider: SpeechProviderWithExtraOptions<string, any>, model: string, input: string, voice: string, providerConfig?: Record<string, any>) => Promise<ArrayBuffer>;
    loadVoicesForProvider: (provider: string, model?: string) => Promise<VoiceInfo[]>;
    getVoicesForProvider: (provider: string) => VoiceInfo[];
    ensureActiveSpeechModel: () => void;
    generateSSML: (text: string, voice: VoiceInfo, providerConfig?: Record<string, unknown>) => string;
    resolveVoicePackSpeechInput: (options: VoicePackSpeechInputOptions) => VoicePackSpeechInput;
    resetState: () => void;
}, "configured" | "supportsModelListing" | "providerModels" | "isLoadingActiveProviderModels" | "activeProviderModelError" | "filteredModels" | "availableSpeechProvidersMetadata" | "supportsSSML">, Pick<{
    configured: import("vue").ComputedRef<boolean>;
    activeSpeechProvider: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeSpeechModel: import("@vueuse/shared").ManualResetRefReturn<string>;
    activeSpeechVoice: import("@vueuse/shared").ManualResetRefReturn<VoiceInfo | undefined>;
    activeSpeechVoiceId: import("@vueuse/shared").ManualResetRefReturn<string>;
    pitch: import("@vueuse/shared").ManualResetRefReturn<number>;
    rate: import("@vueuse/shared").ManualResetRefReturn<number>;
    ssmlEnabled: import("@vueuse/shared").ManualResetRefReturn<boolean>;
    isLoadingSpeechProviderVoices: import("@vueuse/shared").ManualResetRefReturn<boolean>;
    speechProviderError: import("@vueuse/shared").ManualResetRefReturn<string | null>;
    availableVoices: import("@vueuse/shared").ManualResetRefReturn<Record<string, VoiceInfo[]>>;
    modelSearchQuery: import("@vueuse/shared").ManualResetRefReturn<string>;
    availableSpeechProvidersMetadata: import("vue").ComputedRef<import("..").ProviderMetadata[]>;
    supportsSSML: import("vue").ComputedRef<boolean>;
    supportsModelListing: import("vue").ComputedRef<boolean>;
    providerModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    isLoadingActiveProviderModels: import("vue").ComputedRef<boolean>;
    activeProviderModelError: import("vue").ComputedRef<string | null>;
    filteredModels: import("vue").ComputedRef<import("..").ModelInfo[]>;
    speech: (provider: SpeechProviderWithExtraOptions<string, any>, model: string, input: string, voice: string, providerConfig?: Record<string, any>) => Promise<ArrayBuffer>;
    loadVoicesForProvider: (provider: string, model?: string) => Promise<VoiceInfo[]>;
    getVoicesForProvider: (provider: string) => VoiceInfo[];
    ensureActiveSpeechModel: () => void;
    generateSSML: (text: string, voice: VoiceInfo, providerConfig?: Record<string, unknown>) => string;
    resolveVoicePackSpeechInput: (options: VoicePackSpeechInputOptions) => VoicePackSpeechInput;
    resetState: () => void;
}, "resetState" | "speech" | "loadVoicesForProvider" | "getVoicesForProvider" | "ensureActiveSpeechModel" | "generateSSML" | "resolveVoicePackSpeechInput">>;

