// eventa IPC 契约桶 — 按域拆分到 domains/ 后统一 re-export，保持对外路径不变。
export * from './domains/windows'
export * from './domains/widgets'
export * from './domains/plugins'
export * from './domains/mcp'
export * from './domains/memory'
export * from './domains/godot-stage'
export * from './domains/shortcuts'
export * from './domains/stage-three'
export * from './domains/persona'
export * from './domains/overseer'
export * from './domains/connectors'
export * from './domains/sidecar'
export * from './domains/comfyui'
export * from './domains/tts'
export * from './domains/system'
export * from './domains/asr'
export * from './domains/doctor'
export * from './domains/agent-api'
export * from './domains/permission'
export * from './domains/vision'
export * from './domains/executor'
export * from './domains/director'
export * from './domains/coordinator'
export * from './domains/desktop'
export * from './domains/web-tools'

export { electron } from '@kitsune/electron-eventa'
export * from '@kitsune/electron-eventa/electron-updater'
