/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transition-2': RouteRecordInfo<
      '/transition-2',
      '/transition-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transition-3': RouteRecordInfo<
      '/transition-3',
      '/transition-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transition-4': RouteRecordInfo<
      '/transition-4',
      '/transition-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transition-5': RouteRecordInfo<
      '/transition-5',
      '/transition-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transition-6': RouteRecordInfo<
      '/transition-6',
      '/transition-6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/transition-7': RouteRecordInfo<
      '/transition-7',
      '/transition-7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/transition-2.vue': {
      routes:
        | '/transition-2'
      views:
        | never
    }
    'src/pages/transition-3.vue': {
      routes:
        | '/transition-3'
      views:
        | never
    }
    'src/pages/transition-4.vue': {
      routes:
        | '/transition-4'
      views:
        | never
    }
    'src/pages/transition-5.vue': {
      routes:
        | '/transition-5'
      views:
        | never
    }
    'src/pages/transition-6.vue': {
      routes:
        | '/transition-6'
      views:
        | never
    }
    'src/pages/transition-7.vue': {
      routes:
        | '/transition-7'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
